package modbus

type nodeInfo struct {
	organizationCode uint16
	companyCode      uint16
	productType      uint16
	productCode      uint16
	protocolVersion  uint16
	channelAmount    uint16
	nodeSerialNumber uint32
}

type sensorNodeAttachDeviceInfo struct {
	temperature1           uint16
	temperature2           uint16
	temperature3           uint16
	humidity1              uint16
	dewPointSensor         uint16
	rainDetectionSensor    uint16
	flowRateSensor         uint16
	rainFallSensor         uint16
	solarRadiationSensor   uint16
	windSpeedSensor        uint16
	windDirectionSensor    uint16
	voltageSensor          uint16
	co2Sensor              uint16
	ecSensor               uint16
	quantumSensor          uint16
	soilMoistureSensor     uint16
	soilWaterTensionSensor uint16
	pH                     uint16
	soilTemperature        uint16
	temperature4           uint16
	temperature5           uint16
	temperature6           uint16
	temperature7           uint16
	temperature8           uint16
	temperature9           uint16
	temperature10          uint16
	weight1                uint16
	weight2                uint16
}

type sensorNodeStatusInfo struct {
	nodeStatus uint16
}

type sensorStatusInfo struct {
	temperatureSensor1Value      float32
	temperatureSensor1Status     uint16
	temperatureSensor2Value      float32
	temperatureSensor2Status     uint16
	temperatureSensor3Value      float32
	temperatureSensor3Status     uint16
	humiditySensor1Value         float32
	humiditySensor1Status        uint16
	dewPointSensorValue          float32
	dewPointSensorStatus         uint16
	rainDetectionSensorValue     float32
	rainDetectionSensorStatus    uint16
	flowRateSensorValue          float32
	flowRateSensorStatus         uint16
	rainFallSensorValue          float32
	rainFallSensorStatus         uint16
	solarRadiationSensorValue    float32
	solarRadiationSensorStatus   uint16
	windSpeedSensorValue         float32
	windSpeedSensorStatus        uint16
	windDirectionSensorValue     float32
	windDirectionSensorStatus    uint16
	voltageSensorValue           float32
	voltageSensorStatus          uint16
	co2SensorValue               float32
	co2SensorStatus              uint16
	ecSensorValue                float32
	ecSensorStatus               uint16
	quantumSensorValue           float32
	quantumSensorStaus           uint16
	soilMoistureSensorValue      float32
	soilMoistureSensorStatus     uint16
	soilWaterTensionSensorValue  float32
	soilWaterTensionSensorStatus uint16
	pHSensorValue                float32
	pHSensorStatus               uint16
	soilTemperatureSensorValue   float32
	soilTemperatureSensorStatus  uint16
	temperatureSensor4Value      float32
	temperatureSensor4Status     uint16
	temperatureSensor5Value      float32
	temperatureSensor5Status     uint16
	temperatureSensor6Value      float32
	temperatureSensor6Status     uint16
	temperatureSensor7Value      float32
	temperatureSensor7Status     uint16
	temperatureSensor8Value      float32
	temperatureSensor8Status     uint16
	temperatureSensor9Value      float32
	temperatureSensor9Status     uint16
	temperatureSensor10Value     float32
	temperatureSensor10Status    uint16
	weightSensor1Value           float32
	weightSensor1Status          uint16
	weightSensor2Value           float32
	weightSensor2Status          uint16
}

type actuatorNodeAttachDeviceInfo struct {
	switch1                  uint16
	switch2                  uint16
	switch3                  uint16
	switch4                  uint16
	switch5                  uint16
	switch6                  uint16
	switch7                  uint16
	switch8                  uint16
	switch9                  uint16
	switch10                 uint16
	switch11                 uint16
	switch12                 uint16
	switch13                 uint16
	switch14                 uint16
	switch15                 uint16
	switch16                 uint16
	openingAndClosingDevice1 uint16
	openingAndClosingDevice2 uint16
	openingAndClosingDevice3 uint16
	openingAndClosingDevice4 uint16
	openingAndClosingDevice5 uint16
	openingAndClosingDevice6 uint16
	openingAndClosingDevice7 uint16
	openingAndClosingDevice8 uint16
}

type actuatorNodeStatusInfo struct {
	opID0      uint16
	nodeStatus uint16
}

type actuatorNodeOperationInfo struct {
	nodeOperation uint16
	opID0         uint16
}

type actuatorStatusInfo struct {
	opID1                                          uint16
	switch1Status                                  uint16
	switch1RemainingOperationTime                  uint32
	opID2                                          uint16
	switch2Status                                  uint16
	switch2RemainingOperationTime                  uint32
	opID3                                          uint16
	switch3Status                                  uint16
	switch3RemainingOperationTime                  uint32
	opID4                                          uint16
	switch4Status                                  uint16
	switch4RemainingOperationTime                  uint32
	opID5                                          uint16
	switch5Status                                  uint16
	switch5RemainingOperationTime                  uint32
	opID6                                          uint16
	switch6Status                                  uint16
	switch6RemainingOperationTime                  uint32
	opID7                                          uint16
	switch7Status                                  uint16
	switch7RemainingOperationTime                  uint32
	opID8                                          uint16
	switch8Status                                  uint16
	switch8RemainingOperationTime                  uint32
	opID9                                          uint16
	switch9Status                                  uint16
	switch9RemainingOperationTime                  uint32
	opID10                                         uint16
	switch10Status                                 uint16
	switch10RemainingOperationTime                 uint32
	opID11                                         uint16
	switch11Status                                 uint16
	switch11RemainingOperationTime                 uint32
	opID12                                         uint16
	switch12Status                                 uint16
	switch12RemainingOperationTime                 uint32
	opID13                                         uint16
	switch13Status                                 uint16
	switch14RemainingOperationTime                 uint32
	opID15                                         uint16
	switch15Status                                 uint16
	switch15RemainingOperationTime                 uint32
	opID16                                         uint16
	switch16Status                                 uint16
	switch16RemainingOperationTime                 uint32
	opID17                                         uint16
	openingAndClosingDevice1Status                 uint16
	openingAndClosingDevice1RemainingOperationTime uint32
	opID18                                         uint16
	openingAndClosingDevice2Status                 uint16
	openingAndClosingDevice2RemainingOperationTime uint32
	opID19                                         uint16
	openingAndClosingDevice3Status                 uint16
	openingAndClosingDevice3RemainingOperationTime uint32
	opID20                                         uint16
	openingAndClosingDevice4Status                 uint16
	openingAndClosingDevice4RemainingOperationTime uint32
	opID21                                         uint16
	openingAndClosingDevice5Status                 uint16
	openingAndClosingDevice5RemainingOperationTime uint32
	opID22                                         uint16
	openingAndClosingDevice6Status                 uint16
	openingAndClosingDevice6RemainingOperationTime uint32
	opID23                                         uint16
	openingAndClosingDevice7Status                 uint16
	openingAndClosingDevice7RemainingOperationTime uint32
	opID24                                         uint16
	openingAndClosingDevice8Status                 uint16
	openingAndClosingDevice8RemainingOperationTime uint32
}

type actuatorOperationInfo struct {
	switch1Operation                      uint16
	opID1                                 uint16
	switch1OperationTime                  uint32
	switch2Operation                      uint16
	opID2                                 uint16
	switch2OperationTime                  uint32
	switch3Operation                      uint16
	opID3                                 uint16
	switch3OperationTime                  uint32
	switch4Operation                      uint16
	opID4                                 uint16
	switch4OperationTime                  uint32
	switch5Operation                      uint16
	opID5                                 uint16
	switch5OperationTime                  uint32
	switch6Operation                      uint16
	opID6                                 uint16
	switch6OperationTime                  uint32
	switch7Operation                      uint16
	opID7                                 uint16
	switch7OperationTime                  uint32
	switch8Operation                      uint16
	opID8                                 uint16
	switch8OperationTime                  uint32
	switch9Operation                      uint16
	opID9                                 uint16
	switch9OperationTime                  uint32
	switch10Operation                     uint16
	opID10                                uint16
	switch10OperationTime                 uint32
	switch11Operation                     uint16
	opID11                                uint16
	switch11OperationTime                 uint32
	switch12Operation                     uint16
	opID12                                uint16
	switch12OperationTime                 uint32
	switch13Operation                     uint16
	opID13                                uint16
	switch13OperationTime                 uint32
	switch14Operation                     uint16
	opID14                                uint16
	switch14OperationTime                 uint32
	switch15Operation                     uint16
	opID15                                uint16
	switch15OperationTime                 uint32
	switch16Operation                     uint16
	opID16                                uint16
	switch16OperationTime                 uint32
	openingAndClosingDevice1Operation     uint16
	opID17                                uint16
	openingAndClosingDevice1OperationTime uint32
	openingAndClosingDevice2Operation     uint16
	opID18                                uint16
	openingAndClosingDevice2OperationTime uint32
	openingAndClosingDevice3Operation     uint16
	opID19                                uint16
	openingAndClosingDevice3OperationTime uint32
	openingAndClosingDevice4Operation     uint16
	opID20                                uint16
	openingAndClosingDevice4OperationTime uint32
	openingAndClosingDevice5Operation     uint16
	opID21                                uint16
	openingAndClosingDevice5OperationTime uint32
	openingAndClosingDevice6Operation     uint16
	opID22                                uint16
	openingAndClosingDevice6OperationTime uint32
	openingAndClosingDevice7Operation     uint16
	opID23                                uint16
	openingAndClosingDevice7OperationTime uint32
	openingAndClosingDevice8Operation     uint16
	opID24                                uint16
	openingAndClosingDevice8OperationTime uint32
}
